module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/apps/api-e2e',
    '<rootDir>/libs/api/data-access-auth',
    '<rootDir>/libs/api/feature-auth',
    '<rootDir>/libs/api/data-access-core',
    '<rootDir>/libs/api/feature-core',
    '<rootDir>/apps/admin',
    '<rootDir>/libs/admin/assets',
    '<rootDir>/libs/admin/data-access-auth',
    '<rootDir>/libs/admin/data-access-core',
    '<rootDir>/libs/admin/feature-about',
    '<rootDir>/libs/admin/feature-auth',
    '<rootDir>/libs/admin/feature-core',
    '<rootDir>/libs/admin/feature-dashboard',
    '<rootDir>/libs/admin/feature-shell',
    '<rootDir>/libs/admin/layout',
    '<rootDir>/libs/admin/style',
    '<rootDir>/libs/admin/ui-form',
  ],
}
